-- Run this SQL in Supabase Dashboard > SQL Editor.

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  faculty text not null,
  year_level text not null,
  meals_per_day integer not null check (meals_per_day between 1 and 8),
  monthly_food_budget numeric(10,2) not null check (monthly_food_budget >= 0),
  average_meal_spend numeric(10,2) not null check (average_meal_spend >= 0),
  common_meal text not null,
  dining_place text not null,
  delivery_frequency text not null,
  important_factors text[] not null default '{}',
  skip_meal_frequency text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.survey_responses enable row level security;

drop policy if exists "Users can view their own response" on public.survey_responses;
create policy "Users can view their own response"
on public.survey_responses for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own response" on public.survey_responses;
create policy "Users can insert their own response"
on public.survey_responses for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own response" on public.survey_responses;
create policy "Users can update their own response"
on public.survey_responses for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own response" on public.survey_responses;
create policy "Users can delete their own response"
on public.survey_responses for delete to authenticated
using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists survey_responses_updated_at on public.survey_responses;
create trigger survey_responses_updated_at
before update on public.survey_responses
for each row execute function public.set_updated_at();
